### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by yinghung** [gbrian/grafana-simple-sql-datasource#32]
The tables have column name 'Value'. The strange thing is that 'SELECT value FROM Table1' is OK, but 'SELECT value FROM table2' generated 'TypeError: Cannot read property 'name' of undefined'. The exception message is shown as following,

TypeError: Cannot read property 'name' of undefined
    at _.map (C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\dist\serverside\sqlproxyserver.js:209:49)
    at C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\node_modules\lodash\lodash.js:3555:27
    at C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\node_modules\lodash\lodash.js:4917:15
    at baseForOwn (C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\node_modules\lodash\lodash.js:3002:24)
    at C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\node_modules\lodash\lodash.js:4886:18
    at baseMap (C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\node_modules\lodash\lodash.js:3554:7)
    at Function.map (C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\node_modules\lodash\lodash.js:9546:14)
    at Object.parseTable (C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\dist\serverside\sqlproxyserver.js:208:25)
    at _api.internals.try (C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\dist\serverside\sqlproxyserver.js:149:60)
    at Object.try (C:\temp\grafana-5.0.3.windows-x64\grafana-5.0.3\data\plugins\grafana-simple-sql-datasource\dist\serverside\sqlproxyserver.js:139:18)

**Comment by buiductri** [comment]
What is the type of column in table2? I mentioned in #27 and #23 that FLOAT data type having issue with Grafana. Maybe converting to DECIMAL may solve the problem.

**Comment by yinghung** [comment]
It is a float data type. Now it works after casting to decimal data type.
